### ISSUE TITLE
assetmanager warmup Exception

### ISSUE THREAD

**Issue by diemuzi** [RWOverdijk/AssetManager#149]
I'm not sure what other information you may need.

ZF 2.3.3
PHP 5.6.0

Using the latest from Master I'm receiving the following error:

```
[root@admin public]$ php index.php assetmanager warmup
======================================================================
   The application has thrown an exception!
======================================================================
 Zend\ServiceManager\Exception\ServiceNotCreatedException
 While attempting to create assetmanagercontrollerconsole(alias: AssetManager\Controller\Console) an invalid factory was registered for this instance type.
----------------------------------------------------------------------
/vhosts/otwebsoft_admin/vendor/Zend/ServiceManager/AbstractPluginManager.php:209
#0 /vhosts/otwebsoft_admin/vendor/Zend/ServiceManager/ServiceManager.php(612): Zend\ServiceManager\AbstractPluginManager->createFromFactory('assetmanagercon...', 'AssetManager\\Co...')
#1 /vhosts/otwebsoft_admin/vendor/Zend/ServiceManager/ServiceManager.php(572): Zend\ServiceManager\ServiceManager->doCreate('AssetManager\\Co...', 'assetmanagercon...')
#2 /vhosts/otwebsoft_admin/vendor/Zend/ServiceManager/ServiceManager.php(504): Zend\ServiceManager\ServiceManager->create(Array)
#3 /vhosts/otwebsoft_admin/vendor/Zend/ServiceManager/AbstractPluginManager.php(103): Zend\ServiceManager\ServiceManager->get('AssetManager\\Co...', false)
#4 /vhosts/otwebsoft_admin/vendor/Zend/Mvc/Controller/ControllerManager.php(137): Zend\ServiceManager\AbstractPluginManager->get('AssetManager\\Co...', Array, false)
#5 /vhosts/otwebsoft_admin/vendor/Zend/Mvc/DispatchListener.php(97): Zend\Mvc\Controller\ControllerManager->get('AssetManager\\Co...')
#6 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /vhosts/otwebsoft_admin/vendor/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /vhosts/otwebsoft_admin/vendor/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /vhosts/otwebsoft_admin/vendor/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /vhosts/otwebsoft_admin/public/index.php(28): Zend\Mvc\Application->run()
#11 {main}
======================================================================
   Previous Exception(s):
```

**Comment by RWOverdijk** [comment]
@diemuzi Sorry I completely missed this one. Is this still a problem?
